"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_KEY"
files: [
  {
    "source": "/github/workspace/public/.well-known/security.txt",
    "translation": "/github/workspace/crowdin/%locale%/%original_file_name%"
  }
]